export const PROJECTS = [
  {
    title: "Online Coding Platform",
    subtitle: "Full Stack Project (Freelancing)",
    year: "2026",
    icon: "bi-code-slash",
    accent: "#00ffcc",
    desc: "Engineered a scalable coding platform enabling users to enroll in courses, participate in live sessions, and track their learning progress. Designed modular and extensible RESTful APIs for course management, user workflows, and session orchestration. Implemented secure authentication using Google OAuth 2.0. Integrated Redis for high-performance caching and RabbitMQ for asynchronous task processing, ensuring smooth handling of background jobs and real-time operations. Containerized services using Docker to enable consistent deployment and improved system reliability.",
    tags: [
      "Node.js",
      "TypeScript",
      "PostgreSQL",
      "Redis",
      "RabbitMQ",
      "Docker",
      "Google OAuth",
      "REST API",
      "System Design",
    ],
  },
  {
    title: "Communication Service",
    subtitle: "Backend Microservice",
    year: "2025",
    icon: "bi-chat-dots",
    accent: "#00ffcc",
    desc: "Designed and developed a scalable communication microservice to handle multi-channel notifications including Email, SMS, and Firebase Cloud Messaging (FCM). Built to support high-volume message delivery for large user bases, the service enables seamless integration with multiple applications via decoupled APIs. Implemented asynchronous processing using RabbitMQ to efficiently manage bulk messaging and background jobs. Integrated retry mechanisms and failure handling to ensure reliable message delivery. Optimized performance using Redis caching and designed the system for extensibility, allowing easy addition of new communication channels.",
    tags: [
      "Node.js",
      "TypeScript",
      "Microservices",
      "RabbitMQ",
      "Redis",
      "FCM",
      "SMS",
      "Email",
      "REST API",
      "System Design",
    ],
  },
  {
    title: "Game Management System",
    subtitle: "Game Mano Pvt. Ltd",
    year: "2025",
    icon: "bi-controller",
    accent: "#00ffcc",
    desc: "I developed a centralized admin backoffice for casino operations, enabling player management, affiliate systems, and campaign configuration. Built scalable REST APIs, implemented RBAC for secure access control, and integrated Redis, RabbitMQ, and Socket.IO for real-time and background processing.",
    tags: [
      "Node.js",
      "TypeScript",
      "PostgreSQL",
      "Prisma",
      "Redis",
      "RabbitMQ",
      "Socket.IO",
      "AWS S3",
      "BullMQ",
      "Jest",
    ],
  },
  {
    title: "Employee Management Portal",
    subtitle: "MicroSpark Software Solutions",
    year: "2023",
    icon: "bi-people-fill",
    accent: "#00ffcc",
    desc: "I developed backend APIs for an employee management system to handle user data, authentication, and internal workflows. Integrated Firebase notifications, SendGrid emails, and Swagger documentation while ensuring secure access, efficient performance, and smooth frontend integration.",
    tags: ["Node.js", "MongoDB", "Firebase", "SendGrid", "Swagger", "REST API"],
  },
];
